##
## EPITECH PROJECT, 2020
## OOP_arcade_2019
## File description:
## Makefile
##

all:
	make -C solarfox/
	make -C nibbler/

re:
	make re -C solarfox/
	make re -C nibbler/

clean:
	make clean -C solarfox/
	make clean -C nibbler/

fclean:
	make fclean -C solarfox/
	make fclean -C nibbler/