##
## EPITECH PROJECT, 2020
## OOP_arcade_2019
## File description:
## Makefile
##

all:
	make -C solarfox/
	make -C nibbler/
	make -C pacman/
	make -C qix/
	make -C centipede/

re:
	make re -C solarfox/
	make re -C nibbler/
	make re -C pacman/
	make re -C qix/
	make re -C centipede/

clean:
	make clean -C solarfox/
	make clean -C nibbler/
	make clean -C pacman/
	make clean -C qix/
	make clean -C centipede/

fclean:
	make fclean -C solarfox/
	make fclean -C nibbler/
	make fclean -C pacman/
	make fclean -C qix/
	make fclean -C centipede/
