##
## EPITECH PROJECT, 2020
## OOP_arcade_2019
## File description:
## Makefile
##

all:
	make -C sfml/
	make -C ncurses/
	make -C vulkan/

re:
	make re -C sfml/
	make re -C ncurses/
	make re -C vulkan/

clean:
	make clean -C sfml/
	make clean -C ncurses/
	make clean -C vulkan/

fclean:
	make fclean -C sfml/
	make fclean -C ncurses/
	make fclean -C vulkan/
