##
## EPITECH PROJECT, 2020
## OOP_arcade_2019
## File description:
## Makefile
##

all:
	make -C sfml/
	make -C ncurses/
	# make -C sdl2/

re:
	make re -C sfml/
	make re -C ncurses/
	# make re -C sdl2/

clean:
	make clean -C sfml/
	make clean -C ncurses/
	# make clean -C sdl2/

fclean:
	make fclean -C sfml/
	make fclean -C ncurses/
	# make fclean -C sdl2/
