##
## EPITECH PROJECT, 2020
## OOP_arcade_2019
## File description:
## Makefile
##

all:
	make -C sfml/
	# make -C ncurses/

re:
	make re -C sfml/
	# make re -C ncurses/

clean:
	make clean -C sfml/
	# make clean -C ncurses/

fclean:
	make fclean -C sfml/
	# make fclean -C ncurses/